---
title: "amino acid web"
output: html_document
date: "2023-10-04"
---
ATTENTION: remove all
do not click casually
```{r}
rm(list = ls())
```


### data retrieval
```{r}
library(cowplot)
library(ggplot2)
data <- read.table("data/itasser-AAN-feature.txt",sep="\t",header=TRUE)
```

#### histogram
```{r}
betweenness <- data[,c(1,2,7)]
p1 <- ggplot(betweenness,aes(x=POSITION,y=scale(Betweenness),fill=Disease)) + geom_bar(stat = 'identity',width = 2)+xlab("Residues")+ylab("Betweenness")+ theme_cowplot() + theme(legend.position="none") + scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'))
closeness <- data[,c(1,3,7)]
p2 <- ggplot(closeness,aes(x=POSITION,y=Closeness,fill=Disease)) + geom_bar(stat = 'identity',width = 2)+xlab("Residues")+ylab("Closeness")+ theme_cowplot() + theme(legend.position="none") + scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'))
degree <- data[,c(1,4,7)]
p3 <- ggplot(degree,aes(x=POSITION,y=Degree,fill=Disease)) + geom_bar(stat = 'identity',width = 2)+xlab("Residues")+ylab("Degree")+ theme_cowplot() + theme(legend.position="none") + scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'))
evcent <- data[,c(1,5,7)]
p4 <- ggplot(evcent,aes(x=POSITION,y=Eigenvector,fill=Disease)) + geom_bar(stat = 'identity',width = 2)+xlab("Residues")+ylab("Eigenvector")+ theme_cowplot() + theme(legend.position="none") + scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'))
transitivity <- data[,c(1,6,7)]
p5 <- ggplot(transitivity,aes(x=POSITION,y=Clustering_coefficient,fill=Disease)) + geom_bar(stat = 'identity',width = 2)+xlab("Residues")+ylab("Clustering coefficient")+ theme_cowplot() + theme(legend.position="none") + scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'))
```

#### save
```{r}
ggsave(p1, file="Figures/氨基酸网络构建/betweenness.jpg", 
       width = 18, height=4, dpi=1200)
ggsave(p2, file="Figures/氨基酸网络构建/closeness.jpg", 
       width = 18, height=4, dpi=1200)
ggsave(p3, file="Figures/氨基酸网络构建/degree.jpg", 
       width = 18, height=4, dpi=1200)
ggsave(p4, file="Figures/氨基酸网络构建/evcent.jpg", 
       width = 18, height=4, dpi=1200)
ggsave(p5, file="Figures/氨基酸网络构建/clustering.jpg", 
       width = 18, height=4, dpi=1200)
```

#### violin
```{r}
betweenness <- data[,c(1,2,7)]
Betweenness <- scale(betweenness[,2])
betweenness <- betweenness[,-2]
# five categories
betweenness <- cbind(betweenness,Betweenness)
closeness <- data[,c(1,3,7)]
degree <- data[,c(1,4,7)]
evcent <- data[,c(1,5,7)]
transitivity <- data[,c(1,6,7)]
```

```{r}
library(ggpubr)
pv6 <- ggplot(betweenness, aes(x=factor(Disease, levels=c("ASD", "Cancer", "ASD_Cancer", "Control")), y=Betweenness, fill = Disease, color = Disease)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2, fill="white", color="black") +
  scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  scale_color_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  labs(x="Disease", y="betweenness", fill="Disease") +
  theme_minimal()
my_comparisons <- list(c("ASD", "Cancer"), c('ASD', 'ASD_Cancer'), c("ASD", "Control"), c( 'Cancer','ASD_Cancer'), c('Cancer', 'Control'), c('ASD_Cancer','Control'))
#pv6 <- pv6 + scale_y_continuous(limits = c(-0.01,0.045))
pv6 <- pv6 + theme(legend.position = "none",panel.grid = element_blank())
pv6 <- pv6 + stat_compare_means(comparisons = my_comparisons,
                       #label.y = c(0.03,0.033,0.036,0.039,0.042,0.045),
                       method = "wilcox.test")
pv6 <- pv6 + theme(axis.line = element_line(color = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())

```

```{r}
library(ggpubr)
pv7 <- ggplot(closeness, aes(x=factor(Disease, levels=c("ASD", "Cancer", "ASD_Cancer", "Control")), y=Closeness, fill = Disease, color = Disease)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2, fill="white", color="black") +
  scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  scale_color_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  labs(x="Disease", y="Closeness", fill="Disease") +
  theme_minimal()
my_comparisons <- list(c("ASD", "Cancer"), c('ASD', 'ASD_Cancer'), c("ASD", "Control"), c( 'Cancer','ASD_Cancer'), c('Cancer', 'Control'), c('ASD_Cancer','Control'))
#pv6 <- pv6 + scale_y_continuous(limits = c(-0.01,0.045))
pv7 <- pv7 + theme(legend.position = "none",panel.grid = element_blank())
pv7 <- pv7 + stat_compare_means(comparisons = my_comparisons,
                       #label.y = c(0.03,0.033,0.036,0.039,0.042,0.045),
                       method = "wilcox.test")
pv7 <- pv7 + theme(axis.line = element_line(color = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())

```

```{r}
library(ggpubr)
pv8 <- ggplot(degree, aes(x=factor(Disease, levels=c("ASD", "Cancer", "ASD_Cancer", "Control")), y=Degree, fill = Disease, color = Disease)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2, fill="white", color="black") +
  scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  scale_color_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  labs(x="Disease", y="Degree", fill="Disease") +
  theme_minimal()
my_comparisons <- list(c("ASD", "Cancer"), c('ASD', 'ASD_Cancer'), c("ASD", "Control"), c( 'Cancer','ASD_Cancer'), c('Cancer', 'Control'), c('ASD_Cancer','Control'))
#pv6 <- pv6 + scale_y_continuous(limits = c(-0.01,0.045))
pv8 <- pv8 + theme(legend.position = "none",panel.grid = element_blank())
pv8 <- pv8 + stat_compare_means(comparisons = my_comparisons,
                       #label.y = c(0.03,0.033,0.036,0.039,0.042,0.045),
                       method = "wilcox.test")
pv8 <- pv8 + theme(axis.line = element_line(color = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())

```

```{r}
library(ggpubr)
pv9 <- ggplot(evcent, aes(x=factor(Disease, levels=c("ASD", "Cancer", "ASD_Cancer", "Control")), y=Eigenvector, fill = Disease, color = Disease)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2, fill="white", color="black") +
  scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  scale_color_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  labs(x="Disease", y="Evcent", fill="Disease") +
  theme_minimal()
my_comparisons <- list(c("ASD", "Cancer"), c('ASD', 'ASD_Cancer'), c("ASD", "Control"), c( 'Cancer','ASD_Cancer'), c('Cancer', 'Control'), c('ASD_Cancer','Control'))
#pv6 <- pv6 + scale_y_continuous(limits = c(-0.01,0.045))
pv9 <- pv9 + theme(legend.position = "none",panel.grid = element_blank())
pv9 <- pv9 + stat_compare_means(comparisons = my_comparisons,
                       #label.y = c(0.03,0.033,0.036,0.039,0.042,0.045),
                       method = "wilcox.test")
pv9 <- pv9 + theme(axis.line = element_line(color = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())

```

```{r}
library(ggpubr)
pv10 <- ggplot(transitivity, aes(x=factor(Disease, levels=c("ASD", "Cancer", "ASD_Cancer", "Control")), y=Clustering_coefficient, fill = Disease, color = Disease)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2, fill="white", color="black") +
  scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  scale_color_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  labs(x="Disease", y="Transitivity", fill="Disease") +
  theme_minimal()
my_comparisons <- list(c("ASD", "Cancer"), c('ASD', 'ASD_Cancer'), c("ASD", "Control"), c( 'Cancer','ASD_Cancer'), c('Cancer', 'Control'), c('ASD_Cancer','Control'))
#pv6 <- pv6 + scale_y_continuous(limits = c(-0.01,0.045))
pv10 <- pv10 + theme(legend.position = "none",panel.grid = element_blank())
pv10 <- pv10 + stat_compare_means(comparisons = my_comparisons,
                       #label.y = c(0.03,0.033,0.036,0.039,0.042,0.045),
                       method = "wilcox.test")
pv10 <- pv10 + theme(axis.line = element_line(color = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())

```


#### save
```{r}
ggsave <- ggsave(pv6,filename = "Figures/氨基酸网络构建/betweenness_violin.jpg",width = 4,height = 4,dpi = 1200)
ggsave <- ggsave(pv7,filename = "Figures/氨基酸网络构建/closeness_violin.jpg",width =4 ,height = 4,dpi = 1200)
ggsave <- ggsave(pv8,filename = "Figures/氨基酸网络构建/degree_violin.jpg",width = 4,height = 4,dpi = 1200)
ggsave <- ggsave(pv9,filename = "Figures/氨基酸网络构建/evcent_violin.jpg",width = 4,height = 4,dpi = 1200)
ggsave <- ggsave(pv10,filename = "Figures/氨基酸网络构建/clustering_violin.jpg",width = 4,height = 4,dpi = 1200)
```