---
title: "main"
output: html_document
arthor: "Spencer Wang"
date: "2023-09-05"
---

##画饼图

```{r}
dat_per<-read.csv("data/pie.csv", header = T)
#dat_per$Group <- factor(dat_per$Group, levels=dat_per$Group) # 把group一列转化为因子型，并确定因子的顺序
```

```{r}
color_palette_1 <- c('#A1A9D0','#F0988C','#B883D4','#9E9E9E')
data_pie <- data.frame(
  Diseases = c("ASD", "Cancer", "ASD_Cancer", "Control"),
  count = c(134,427,41,22)
)

p_pie <- ggplot(data = data_pie, mapping = aes(x = '', y = count, fill = Diseases)) + 
  geom_bar(stat = 'identity', position = 'stack',width = 1) +
  coord_polar(theta = 'y') +
  theme(legend.position = "none",panel.grid = element_blank())+
  labs(x = '', y = '', title = '') +
  theme(axis.text = element_blank()) +
  scale_fill_manual(values = color_palette_1, limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control'),drop = FALSE)+
  theme_minimal()
```

```{r}
ggsave(p_pie, file="Figures/pie.jpg", 
       width = 7, height=7, dpi=1200)
```

## Entropy

### data process
```{r}
color_palette <- c("#8ECFC9", "#FFBE7A", "#FA7F6F", "#82B0D2")
color_palette_1 <- c('#A1A9D0','#F0988C','#B883D4','#9E9E9E')
shape_palette_1 <- c(1,2,3,4)
```


```{r}
all_en <- read.table("../data/Si.csv",sep = ',',header = T)
colnames(all_en) <- c("residue","entropy")
```

```{r}
library(ggplot2)
coco <- read.csv('../data/entropy1.csv')
coco <- coco[order(coco$residue), ]
#coco <- coco[!duplicated(coco$residue), ]

data <- read.csv('../data/entropy1.csv')
data <- merge(all_en,data,by = "residue",all  = T)
data <- data[order(data$residue), ]
data <- data[!duplicated(data$residue), ]
rownames(data) <- 1:403
colnames(data) <- c("residue","all_entropy","entropy","disease")
breaks <- c(0, 15, 184, 189, 350, 403)
Region <- cut(data$residue, breaks, 
                   labels = c("PBD", "PD", " ", "C2D", "CTT"), 
                   include.lowest = TRUE)
data_en <- cbind(data,Region)
```

```{r}
start <- c(0, 16, 185, 190, 351)
end <- c(16, 185, 190, 351, 403)
for (i in 1:nrow(data_en)) {
  if (data_en$Region[i] == "PBD") {
    data_en$start[i] <- start[1]
    data_en$end[i] <- end[1]
  } else if (data_en$Region[i] == "PD") {
    data_en$start[i] <- start[2]
    data_en$end[i]<-  end[2]
  }else if (data_en$Region[i] == " ") {
    data_en$start[i] <- start[3]
    data_en$end[i]<-  end[3]
  } else if (data_en$Region[i] == "C2D") {
    data_en$start[i] <- start[4]
    data_en$end[i] <- end[4]
  } else if (data_en$Region[i] == "CTT") {
    data_en$start[i] <- start[5]
    data_en$end[i] <- end[5]
  }
}
```

### 位点计算
```{r}
p_en <- ggplot(data_en, aes(x = residue, y = all_entropy)) + 
 geom_bar(stat = "identity",
           color = "transparent", 
           fill = "grey")+
  
  labs(x="Residues", y="S(i)", color="Diseases", shape="Diseases") + 
  theme_bw()

p_en <- p_en + geom_point(data=coco,aes(x=residue,y=entropy,color=disease),size=2.8,pch=19) + scale_colour_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),breaks = c("ASD", "Cancer", "ASD_Cancer", "Control"))

p_en <- p_en + scale_x_continuous(limits = c(0,410)) + scale_y_continuous(limits = c(-0.3,2.6))
p_en <- p_en + geom_rect(data = data_en, aes(xmin = start, xmax = end, ymin = -0.3, ymax = 0, fill = Region),color = "transparent") +
  scale_fill_manual(values = c("PBD" = "#8ECFC9", "PD" = "#FFBE7A"," " = "transparent", "C2D" = "#FA7F6F", "CTT" = "#82B0D2")) +
  geom_text(aes(x = start + (end - start)/2, y = -0.22, label = Region), vjust = 0, color = 'black',size = 5) +
  geom_segment(aes(x = 185, y = -0.15, xend = 190, yend = -0.15), color = "grey", linetype = "solid", size = 1)+
  theme_minimal()
p_en <- p_en + theme(panel.border = element_rect(linetype = 'solid', colour = 'black',fill = NA,size = 0.7),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
p_en <- p_en + theme(legend.position = "none",panel.grid = element_blank())
```



```{r}
ggsave(p_en, file="../Figures/figure1/Entropy.jpg", 
       width = 11.2, height=4, dpi=1200)
```

###entropy的小提琴图
```{r}
library(ggplot2)
library(dplyr)
library(ggsignif)
```

```{r}
# 绘制小提琴图
library(ggpubr)
p1 <- ggplot(coco, aes(x=factor(disease, levels=c("ASD", "Cancer", "ASD_Cancer", "Control")), y=entropy, fill=disease, color = disease)) +
  geom_violin(trim=FALSE) +
  theme(legend.position = "none") +
  theme(panel.border = element_blank()) +
  geom_boxplot(width=0.2, fill="white", color="black") +
  scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  scale_color_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  labs(x="Disease", y="S(i)", fill="Disease") +
  theme_classic()
my_comparisons <- list(c("ASD", "Cancer"), c('ASD', 'ASD_Cancer'), c("ASD", "Control"), c( 'Cancer','ASD_Cancer'), c('Cancer', 'Control'), c('ASD_Cancer','Control'))
p1 <- p1 + stat_compare_means(comparisons = my_comparisons,
                       label.y = c(1.5,1.75,2.18,1.5,1.97,1.5),
                       method = "wilcox.test")
p1 <- p1 + theme(legend.position = "none",panel.grid = element_blank())
p1 <- p1 + theme(
                 panel.border = element_rect(linetype = 'solid', colour = 'black',fill = NA,size = 0.7),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
```

```{r}
ggsave(p1, file="Figures/figure1/Entropy_violin.jpg", 
       width = 4, height = 4, dpi=1200)
```

## Consurf
### data process
```{r}
library(ggplot2)
library(dplyr)
library(ggsignif)
data <- read.csv('data/consurf5.csv')
breaks <- c(0, 15, 189, 350, 403)
Region <- cut(data$residue, breaks, 
                   labels = c("PBD", "PD", "C2D", "CTT"),                                           
                   include.lowest = TRUE)

data_surf <- data.frame(data$residue,data$consurfgrade,data$disease,Region)
start <- c(0, 16, 190, 351)
end <- c(16, 190, 351, 403)
for (i in 1:nrow(data_surf)) {
  if (data_surf$Region[i] == "PBD") {
    data_surf$start[i] <- start[1]
    data_surf$end[i] <- end[1]
  } else if (data_surf$Region[i] == "PD") {
    data_surf$start[i] <- start[2]
    data_surf$end[i]<-  end[2]
  } else if (data_surf$Region[i] == "C2D") {
    data_surf$start[i] <- start[3]
    data_surf$end[i] <- end[3]
  } else if (data_surf$Region[i] == "CTT") {
    data_surf$start[i] <- start[4]
    data_surf$end[i] <- end[4]
  }
}
```

###consurf violin
```{r}
# 绘制小提琴图
library(ggpubr)
p3 <- ggplot(data, aes(x=factor(disease, levels=c("ASD", "Cancer", "ASD_Cancer", "Control")), y=consurfgrade, fill=disease, color = disease)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2, fill="white", color="black") +
  scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  scale_color_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  labs(x="Disease", y="Consurfgrade", fill="Disease") +
  theme_minimal()
my_comparisons <- list(c("ASD", "Cancer"), c('ASD', 'ASD_Cancer'), c("ASD", "Control"), c( 'Cancer','ASD_Cancer'), c('Cancer', 'Control'), c('ASD_Cancer','Control'))
p3 <- p3 + scale_y_continuous(limits = c(4,12.75))
p3 <- p3 + theme(legend.position = "none",panel.grid = element_blank())
p3 <- p3 + stat_compare_means(comparisons = my_comparisons,
                       label.y = c(11,11.5,12.55,11,12.05,11),
                       method = "wilcox.test")
p3 <- p3  + theme(panel.border = element_rect(linetype = 'solid', colour = 'black',fill = NA,size = 0.7),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
```

```{r}
ggsave(p3, file="Figures/figure1/Consurfgrade_violin.jpg", 
       width = 4, height=4, dpi=1200)
```
### 位点计算
```{r}
p_surf <- ggplot(data_surf, aes(x=data.residue, y=data.consurfgrade, group=data.disease, color=data.disease)) + 
  geom_segment(aes(xend=data.residue, yend=0), size=0.6) +
  geom_segment(aes(xend=data.residue, yend=data.consurfgrade), size=0.6) +
  geom_point(size=2) + 
  #scale_shape_manual(values=shape_palette, drop = FALSE) + 
  scale_color_manual(values=color_palette_1, limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control'),drop = FALSE) +
  labs(x="Residues", y="MI", color="Diseases", shape="Diseases") + 
  #theme(plot.title = element_text(hjust = 0.5)) + 
  theme_bw()
p_surf <- p_surf + scale_x_continuous(limits = c(0,410)) + scale_y_continuous(limits = c(-0.6,10))
# df_filter <- filter(Cancer, !is.na(cancer_region) & !is.na(start) & !is.na(end))
p_surf <- p_surf + geom_rect(data = data_surf, aes(xmin = start, xmax = end, ymin = -1.0, ymax = 0, fill = Region),color = "transparent") +
  scale_fill_manual(values = c("PBD" = "#8ECFC9", "PD" = "#FFBE7A", "C2D" = "#FA7F6F", "CTT" = "#82B0D2")) +
  #scale_color_manual(values = c("PBD" = "#8ECFC9", "PD" = "#FFBE7A", "C2D" = "#FA7F6F", "CTT" = "#82B0D2")) +
  geom_text(aes(x = start + (end - start)/2, y = -0.6, label = Region), vjust = 0, color = 'black',size = 5) +
  theme_minimal()
p_surf <- p_surf + theme(axis.line = element_line(color = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
p_surf <- p_surf + theme(legend.position = "none",panel.grid = element_blank())
```

```{r}
ggsave(p_surf, file="Figures/Consurfgrade.jpg", 
       width = 10, height=3, dpi=1200)

```



```{r}
library(patchwork)
p <- p1 + p2 +p3
ggsave(p, file="Figures/violin.jpg", 
       width = 21, height=7, dpi=800)
```

## Coevolution
### data process

```{r}
all_co <- read.table("../data/MI.csv",sep = ',',header = T)
```

```{r}
library(ggplot2)
coco <- read.csv('../data/coevolution.csv')
coco <- coco[order(coco$residue), ]
#coco <- coco[!duplicated(coco$residue), ]

data <- read.csv('../data/coevolution.csv')
data <- merge(all_co,data,by = "residue",all  = T)
data <- data[order(data$residue), ]
data <- data[!duplicated(data$residue), ]
rownames(data) <- 1:403
colnames(data) <- c("residue","all_coevolution","coevolution","disease")
breaks <- c(0, 15, 184, 189, 350, 403)
Region <- cut(data$residue, breaks, 
                   labels = c("PBD", "PD", " ", "C2D", "CTT"), 
                   include.lowest = TRUE)
data_co <- cbind(data,Region)
```

```{r}
start <- c(0, 16, 185, 190, 351)
end <- c(16, 185, 190, 351, 403)
for (i in 1:nrow(data_co)) {
  if (data_co$Region[i] == "PBD") {
    data_co$start[i] <- start[1]
    data_co$end[i] <- end[1]
  } else if (data_co$Region[i] == "PD") {
    data_co$start[i] <- start[2]
    data_co$end[i]<-  end[2]
  }else if (data_co$Region[i] == " ") {
    data_co$start[i] <- start[3]
    data_co$end[i]<-  end[3]
  } else if (data_co$Region[i] == "C2D") {
    data_co$start[i] <- start[4]
    data_co$end[i] <- end[4]
  } else if (data_co$Region[i] == "CTT") {
    data_co$start[i] <- start[5]
    data_co$end[i] <- end[5]
  }
}
```

### 位点计算
```{r}
p_co <- ggplot(data_co, aes(x = residue, y = all_coevolution)) + 
 geom_bar(stat = "identity",
           color = "transparent", 
           fill = "grey")+
  
  labs(x="Residues", y="MI", color="Diseases", shape="Diseases") + 
  theme_bw()

p_co <- p_co + geom_point(data=coco,aes(x=residue,y=coevolution,color=disease),size=2.8,pch=19) + scale_colour_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),breaks = c("ASD", "Cancer", "ASD_Cancer", "Control")) 


p_co <- p_co + scale_x_continuous(limits = c(0,410)) + scale_y_continuous(limits = c(-0.072,0.7))
p_co <- p_co + geom_rect(data = data_co, aes(xmin = start, xmax = end, ymin = -0.072, ymax = 0, fill = Region),color = "transparent") +
  scale_fill_manual(values = c("PBD" = "#8ECFC9", "PD" = "#FFBE7A"," " = "transparent", "C2D" = "#FA7F6F", "CTT" = "#82B0D2")) +
  geom_text(aes(x = start + (end - start)/2, y = -0.053, label = Region), vjust = 0, color = 'black',size = 5) +
  geom_segment(aes(x = 185, y = -0.036, xend = 190, yend = -0.035), color = "grey", linetype = "solid", size = 1)+
  theme_minimal()

p_co <- p_co + theme(panel.border = element_rect(linetype = 'solid', colour = 'black',fill = NA,size = 0.7),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
p_co <- p_co + theme(legend.position = "none",panel.grid = element_blank())
```

### 结构域分布 
```{r}
p_domian <- ggplot(data_co, aes(x=data.residue, y=data.coevolution, group=data.disease, color=data.disease)) + 
  geom_rect(data = data_co, aes(xmin = start, xmax = end, ymin = 0, ymax = 0.15, fill = Region),color = "transparent") +
  scale_fill_manual(values = c("PBD" = "#8ECFC9", "PD" = "#FFBE7A", " "= "transparent"  ,"C2D" = "#FA7F6F", "CTT" = "#82B0D2")) +
  #scale_color_manual(values = c("PBD" = "#8ECFC9", "PD" = "#FFBE7A", "C2D" = "#FA7F6F", "CTT" = "#82B0D2")) +
  geom_text(aes(x = start + (end - start)/2, y = 0.06, label = Region), vjust = 0, color = 'black',size = 5) +
  theme_minimal()+
  geom_segment(aes(x = 185, y = 0.075, xend = 190, yend = 0.075), color = "grey", linetype = "solid", size = 1)+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank())
```

```{r}
ggsave(p_domian, file="Figures/domian.jpg", 
       width = 12, height=3, dpi=1200)
```

```{r}
ggsave(p_co, file="../Figures/figure1/coevolution.jpg", 
       width = 11.2, height=4, dpi=1200)
```

###画coevolution的小提琴图

```{r}
library(ggplot2)
library(dplyr)
library(ggsignif)
```

```{r}
# 绘制小提琴图
library(ggpubr)
p2 <- ggplot(coco, aes(x=factor(disease, levels=c("ASD", "Cancer", "ASD_Cancer", "Control")), y=coevolution, fill=disease, color = disease)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2, fill="white", color="black") +
  scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  scale_color_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  labs(x="Disease", y="MI", fill="Disease") +
  theme_minimal()
my_comparisons <- list(c("ASD", "Cancer"), c('ASD', 'ASD_Cancer'), c("ASD", "Control"), c( 'Cancer','ASD_Cancer'), c('Cancer', 'Control'), c('ASD_Cancer','Control'))
p2 <- p2 + scale_y_continuous(limits = c(-0.25,1.425))
p2 <- p2 + theme(legend.position = "none",panel.grid = element_blank())
p2 <- p2 + stat_compare_means(comparisons = my_comparisons,
                       label.y = c(1.0,1.125,1.375,1.0,1.25,1.0),
                       method = "wilcox.test")
p2 <- p2 + theme(panel.border = element_rect(linetype = 'solid', colour = 'black',fill = NA,size = 0.7),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
```

```{r}
ggsave(p2, file="Figures/figure1/Coevolution_violin.jpg", 
       width = 4, height=4, dpi=1200)
```


##制结构域分布图

```{r}
library(ggplot2)
data <- read.csv('data/residue/residue.csv')
```

####Cancer

```{r}
cancer <- data$Cancer
breaks <- c(0, 15, 184, 189, 350, 403)
Region <- cut(cancer, breaks, 
                   labels = c("PBD", "PD", " ", "C2D", "CTT"), 
                   include.lowest = TRUE)

Cancer <- data.frame(cancer,Region)
library(dplyr)
Cancer <- Cancer %>% 
  group_by(cancer) %>% 
  summarise(count = n(), Region = first(Region))
Cancer <- na.omit(Cancer)
start <- c(0, 16, 185, 190, 351)
end <- c(16, 185, 190, 351, 403)
for (i in 1:nrow(Cancer)) {
  if (Cancer$Region[i] == "PBD") {
    Cancer$start[i] <- start[1]
    Cancer$end[i] <- end[1]
  } else if (Cancer$Region[i] == "PD") {
    Cancer$start[i] <- start[2]
    Cancer$end[i] <- end[2]
  } else if (Cancer$Region[i] == " ") {
    Cancer$start[i] <- start[3]
    Cancer$end[i] <- end[3]
  } else if (Cancer$Region[i] == "C2D") {
    Cancer$start[i] <- start[4]
    Cancer$end[i] <- end[4]
  } else if (Cancer$Region[i] == "CTT") {
    Cancer$start[i] <- start[5]
    Cancer$end[i] <- end[5]
  }
}
```

####ASD

```{r}
asd <- data$ASD
breaks <- c(0, 15, 184, 189, 350, 403)
Region <- cut(asd, breaks, 
                   labels = c("PBD", "PD", " ", "C2D", "CTT"), 
                   include.lowest = TRUE)

ASD <- data.frame(asd,Region)
library(dplyr)
ASD <- ASD %>% 
  group_by(asd) %>% 
  summarise(count = n(), Region = first(Region))
ASD <- na.omit(ASD)
start <- c(0, 16, 185, 190, 351)
end <- c(16, 185, 190, 351, 403)
for (i in 1:nrow(ASD)) {
  if (ASD$Region[i] == "PBD") {
    ASD$start[i] <- start[1]
    ASD$end[i] <- end[1]
  } else if (ASD$Region[i] == "PD") {
    ASD$start[i] <- start[2]
    ASD$end[i] <- end[2]
  } else if (ASD$Region[i] == " ") {
    ASD$start[i] <- start[3]
    ASD$end[i] <- end[3]
  } else if (ASD$Region[i] == "C2D") {
    ASD$start[i] <- start[4]
    ASD$end[i] <- end[4]
  } else if (ASD$Region[i] == "CTT") {
    ASD$start[i] <- start[5]
    ASD$end[i] <- end[5]
  }
}
```

####ASD_Cancer

```{r}
ac <- data$ASD_Cancer
breaks <- c(0, 15, 184, 189, 350, 403)
Region <- cut(ac, breaks, 
                   labels = c("PBD", "PD", " ", "C2D", "CTT"), 
                   include.lowest = TRUE)

AC <- data.frame(ac,Region)
library(dplyr)
AC <- AC %>% 
  group_by(ac) %>% 
  summarise(count = n(), Region = first(Region))
AC <- na.omit(AC)
start <- c(0, 16, 185, 190, 351)
end <- c(16, 185, 190, 351, 403)
for (i in 1:nrow(AC)) {
  if (AC$Region[i] == "PBD") {
    AC$start[i] <- start[1]
    AC$end[i] <- end[1]
  } else if (AC$Region[i] == "PD") {
    AC$start[i] <- start[2]
    AC$end[i] <- end[2]
  } else if (AC$Region[i] == " ") {
    AC$start[i] <- start[3]
    AC$end[i] <- end[3]
  } else if (AC$Region[i] == "C2D") {
    AC$start[i] <- start[4]
    AC$end[i] <- end[4]
  } else if (AC$Region[i] == "CTT") {
    AC$start[i] <- start[5]
    AC$end[i] <- end[5]
  }
}
```

####Control

```{r}
control <- data$Control
breaks <- c(0, 15, 184, 189, 350, 403)
Region <- cut(control, breaks, 
                   labels = c("PBD", "PD", " ", "C2D", "CTT"), 
                   include.lowest = TRUE)

Control <- data.frame(control,Region)
library(dplyr)
Control <- Control %>% 
  group_by(control) %>% 
  summarise(count = n(), Region = first(Region))
Control <- na.omit(Control)
start <- c(0, 16, 185, 190, 351)
end <- c(16, 185, 190, 351, 403)
for (i in 1:nrow(Control)) {
  if (Control$Region[i] == "PBD") {
    Control$start[i] <- start[1]
    Control$end[i] <- end[1]
  } else if (Control$Region[i] == "PD") {
    Control$start[i] <- start[2]
    Control$end[i] <- end[2]
  } else if (Control$Region[i] == " ") {
    Control$start[i] <- start[3]
    Control$end[i] <- end[3]
  } else if (Control$Region[i] == "C2D") {
    Control$start[i] <- start[4]
    Control$end[i] <- end[4]
  } else if (Control$Region[i] == "CTT") {
    Control$start[i] <- start[5]
    Control$end[i] <- end[5]
  }
}
```

#### 设置一些参数

```{r}
color_palette <- c("#8ECFC9", "#FFBE7A", "#FA7F6F", "#82B0D2")
values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E')
shape_palette <- c(1,2,3,4,5)
```

#### Cancer

```{r}
p_1 <- ggplot(Cancer, aes(x=cancer, y=count, group=Region, color=Region)) + 
  geom_segment(aes(xend=cancer, yend=0), linewidth=0.6) +
  geom_segment(aes(xend=cancer, yend=count), linewidth=0.6) +
  geom_point(size=2) + 
  #scale_shape_manual(values=shape_palette, drop = FALSE) + 
  scale_color_manual(values=c('#A1A9D0','#A1A9D0','#A1A9D0','#A1A9D0','#A1A9D0'), drop = FALSE) +
  labs(x = NULL, y="Cancer", color="Region", shape="Region") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_bw()
p_1 <- p_1 + scale_x_continuous(limits = c(0,410)) + scale_y_continuous(limits = c(-1.8,6))
# df_filter <- filter(Cancer, !is.na(cancer_region) & !is.na(start) & !is.na(end))
p_1 <- p_1 + geom_rect(data = Cancer, aes(xmin = start, xmax = end, ymin = -1.8, ymax = 0, fill = Region),color = 'transparent') +
  scale_fill_manual(values = c("PBD" = "#8ECFC9", "PD" = "#FFBE7A"," " = "transparent" ,"C2D" = "#FA7F6F", "CTT" = "#82B0D2")) +
  geom_text(aes(x = start + (end - start)/2, y = -1.5, label = Region), vjust = 0, color = 'black',size = 5) +
  theme_minimal() +
  geom_segment(aes(x = 185, y = -0.9, xend = 190, yend = -0.9), color = "grey", linetype = "solid", size = 1)
p_1 <- p_1 + theme(panel.border = element_rect(linetype = 'solid', colour = 'black',fill = NA,size = 0.7),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
p_1 <- p_1 + theme(legend.position = "none",panel.grid = element_blank())
p_1 <- p_1 + theme(axis.text.x = element_blank())
```

```{r}
ggsave(p_1, file="Figures/Cancer_site.jpg", 
       width = 10, height=1.5, dpi=800)
```

#### ASD

```{r}
p_2 <- ggplot(ASD, aes(x=asd, y=count, group=Region, color=Region)) + 
  geom_segment(aes(xend=asd, yend=0), linewidth=0.6) +
  geom_segment(aes(xend=asd, yend=count), linewidth=0.6) +
  geom_point(size=2) + 
  #scale_shape_manual(values=shape_palette, drop = FALSE) + 
  scale_color_manual(values=c('#F0988C','#F0988C','#F0988C','#F0988C','#F0988C'), drop = FALSE) +
  labs(x = NULL,y="ASD", color="Region", shape="Region") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_bw()
p_2 <- p_2 + scale_x_continuous(limits = c(0,410))+ scale_y_continuous(limits = c(-1.8,6))
# df_filter <- filter(Cancer, !is.na(cancer_region) & !is.na(start) & !is.na(end))
p_2 <- p_2 + geom_rect(data = ASD, aes(xmin = start, xmax = end, ymin = -1.8, ymax = 0, fill = Region),color = 'transparent') +
  scale_fill_manual(values = c("PBD" = "#8ECFC9", "PD" = "#FFBE7A"," " = "transparent", "C2D" = "#FA7F6F", "CTT" = "#82B0D2")) +
 geom_text(aes(x = start + (end - start)/2, y = -1.5, label = Region), vjust = 0, color = 'black',size = 5) +
  theme_minimal()+
  geom_segment(aes(x = 185, y = -0.9, xend = 190, yend = -0.9), color = "grey", linetype = "solid", size = 1)
p_2 <- p_2 + theme(panel.border = element_rect(linetype = 'solid', colour = 'black',fill = NA,size = 0.7),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
p_2 <- p_2 + theme(legend.position = "none",panel.grid = element_blank())
p_2 <- p_2 + theme(axis.text.x = element_blank())
```

```{r}
ggsave(p, file="Figures/ASD_site.jpg", 
       width = 10, height=1.5, dpi=800)
```

#### ASD_Cancer

```{r}
p_3 <- ggplot(AC, aes(x=ac, y=count, group=Region, color=Region)) + 
  geom_segment(aes(xend=ac, yend=0), linewidth=0.6) +
  geom_segment(aes(xend=ac, yend=count), linewidth=0.6) +
  geom_point(size=2) + 
  #scale_shape_manual(values=shape_palette, drop = FALSE) + 
  scale_color_manual(values=c('#B883D4','#B883D4','#B883D4','#B883D4','#B883D4'), drop = FALSE) +
  labs(x = NULL,y="ASD_Cancer", color="Region", shape="Region") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_bw()
p_3 <- p_3 + scale_x_continuous(limits = c(0,410)) + scale_y_continuous(limits = c(-1.8,6))
# df_filter <- filter(Cancer, !is.na(cancer_region) & !is.na(start) & !is.na(end))
p_3 <- p_3 + geom_rect(data = AC, aes(xmin = start, xmax = end, ymin = -1.8, ymax = 0, fill = Region),color = 'transparent') +
  scale_fill_manual(values = c("PBD" = "#8ECFC9", "PD" = "#FFBE7A"," " = "transparent" ,"C2D" = "#FA7F6F", "CTT" = "#82B0D2")) +
  geom_text(aes(x = start + (end - start)/2, y = -1.5, label = Region), vjust = 0, color = 'black',size = 5) +
  theme_minimal()+
  geom_segment(aes(x = 185, y = -0.9, xend = 190, yend = -0.9), color = "grey", linetype = "solid", size = 1)
p_3 <- p_3 + theme(panel.border = element_rect(linetype = 'solid', colour = 'black',fill = NA,size = 0.7),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
p_3 <- p_3 + theme(legend.position = "none",panel.grid = element_blank())
p_3 <- p_3 + theme(axis.text.x = element_blank())
```

```{r}
ggsave(p, file="Figures/ASD_Cancer_site.jpg", 
       width = 10, height=1.5, dpi=800)
```

#### Control

```{r}
p_4 <- ggplot(Control, aes(x=control, y=count, group=Region, color=Region)) + 
  geom_segment(aes(xend=control, yend=0), linewidth=0.6) +
  geom_segment(aes(xend=control, yend=count), linewidth=0.6) +
  geom_point(size=2) + 
  #scale_shape_manual(values=shape_palette, drop = FALSE) + 
  scale_color_manual(values=c('#9E9E9E','#9E9E9E','#9E9E9E','#9E9E9E','#9E9E9E'), drop = FALSE) +
  labs(x = NULL,y="Control", color="Region", shape="Region") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_bw()
p_4 <- p_4 + scale_x_continuous(limits = c(0,410)) 
# df_filter <- filter(Cancer, !is.na(cancer_region) & !is.na(start) & !is.na(end))
p_4 <- p_4 + geom_rect(data = Control, aes(xmin = start, xmax = end, ymin = -1.8, ymax = 0, fill = Region),color = 'transparent') +
  scale_fill_manual(values = c("PBD" = "#8ECFC9", "PD" = "#FFBE7A", " " = "transparent", "C2D" = "#FA7F6F", "CTT" = "#82B0D2")) +
  geom_text(aes(x = start + (end - start)/2, y = -1.5, label = Region), vjust = 0, color = 'black', size = 5) +
  scale_y_continuous(breaks = seq(0, 10, 1), labels = function(x) format(x, scientific = FALSE)) +
  theme_minimal()+
  geom_segment(aes(x = 185, y = -0.9, xend = 190, yend = -0.9), color = "grey", linetype = "solid", size = 1)
p_4 <- p_4 + scale_y_continuous(limits = c(-1.8,6))
p_4 <- p_4 + theme(panel.border = element_rect(linetype = 'solid', colour = 'black',fill = NA,size = 0.7),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
p_4 <- p_4 + theme(legend.position = "none",panel.grid = element_blank())
#p_4 <- p_4 + theme(axis.text.x = element_blank())
```

```{r}
ggsave(p, file="Figures/Control_site.jpg", 
       width = 10, height=1.5, dpi=800)
```

#### 合并

```{r}
library(patchwork)
p <- p_2 / p_1 / p_3 / p_4
ggsave(p, file="Figures/figure1/site.jpg", 
       width = 12, height=6, dpi=1200)
```



## 画柱状图
```{r}
library(ggplot2)

data <- data.frame(
  Group = c("ASD", "ASD", "Cancer", "Cancer", "ASD_Cancer", "ASD_Cancer", "Control", "Control"),
  Data = c(80, 20, 156, 90, 30, 4, 12, 9)
)

color_scheme <- c('#A1A9D0','#F0988C','#B883D4','#9E9E9E')
p_hist <- ggplot(data, aes(x = factor(Group, levels = c("ASD", "Cancer", "ASD_Cancer", "Control")), y = Data, fill = Group)) +
  geom_bar(stat = "identity", position = "stack", alpha = ifelse(data$Data %in% c(20, 90, 4, 9), 0.35, 1)) + # 调整颜色的深浅
  scale_fill_manual(values = color_scheme, limits = c("ASD", "Cancer", 'ASD_Cancer', 'Control'), drop = FALSE) +
  labs(x = '', y = "Count", caption = "") +
  guides(color = 'none') +
  theme_minimal() +
  theme(panel.border = element_rect(linetype = 'solid', colour = 'black',fill = NA,size = 0.7),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())+
  theme(legend.position = "none",panel.grid = element_blank())

p_hist

```

```{r}
ggsave(p_hist, file="Figures/figure1/histogram2.jpg", 
       width = 4, height=4, dpi=1200)
```