---
title: "Total energy"
output: html_document
date: "2023-10-04"
---
```{r}
rm(list = ls())
```

## histogram
```{r}
data_tt <- read.table("../data/itasser-totalenergy.txt",sep="\t",header=TRUE)
library(ggplot2)
library(cowplot)
```

```{r}
p_tt <- ggplot(data_tt,aes(x=res_id,y=scale(itasser_total_energy),fill=disease)) + geom_bar(stat = 'identity',width = 2)+xlab("Residue Number")+ylab("ΔΔG")+ theme_cowplot() + theme(axis.line = element_blank(),panel.border = element_rect(linetype = 'solid', colour = 'black',fill = NA,size = 1),legend.position="none") + scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'))
```


```{r}
ggsave(p_tt, file="../Figures/Total Energy/TTE.jpg", 
       width = 9, height=4, dpi=1200)
```

## violin
```{r}
# 绘制小提琴图
library(ggpubr)
p_ttv <- ggplot(data_tt, aes(x=factor(disease, levels=c("ASD", "Cancer", "ASD_Cancer", "Control")), y=itasser_total_energy, fill=disease, color = disease)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2, fill="white", color="black") +
  scale_fill_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  scale_color_manual(values=c('#A1A9D0','#F0988C','#B883D4','#9E9E9E'),limits=c("ASD", "Cancer", 'ASD_Cancer', 'Control')) +
  labs(x="Disease", y="ΔΔG", fill="Disease") +
  theme_minimal()
my_comparisons <- list(c("ASD", "Cancer"), c('ASD', 'ASD_Cancer'), c("ASD", "Control"), c( 'Cancer','ASD_Cancer'), c('Cancer', 'Control'), c('ASD_Cancer','Control'))
#p_ttv <- p_ttv + scale_y_continuous(limits = c(4,12.75))
p_ttv <- p_ttv + theme(legend.position = "none",panel.grid = element_blank())
p_ttv <- p_ttv + stat_compare_means(comparisons = my_comparisons,
                       label.y = c(44,48,57,44,53,44),
                       method = "wilcox.test")
p_ttv <- p_ttv  + theme(panel.border = element_rect(linetype = 'solid', colour = 'black',fill = NA,size = 0.7),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
```

```{r}
ggsave(p_ttv, file="../Figures/Total Energy/TTV.jpg", 
       width = 4, height=4, dpi=1200)
```



